includes:
  - base.yaml
model:
  model_name: GMTvGIN
ood:
  ood_alg: GMT
  ood_param: 1.0    # info loss coefficient
  extra_param:
    - "bern"    # sampling method
    - 20      # decay_interval
    - 0.7     # final_r
    - 10     # sample_rounds
train:
  max_epoch: 200
  lr: 1e-3


